### ISSUE TITLE
Set attendee limit for 36°N

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#1]
Report here what the attendee limit would be at 36°N.

* Community Hall + Co-working area
* Classroom
* "Lounge"

**Comment by shaneseslaton** [comment]
I will update the capacity number for the areas above prior to the next meeting.

**Comment by shaneseslaton** [comment]
Below are the estimates for capacity in each space: 
Community Hall + Co-working area: 120 comfortably, 140 utilizing every little space
Classroom: 20
"Lounge":15 with current furniture, could add chairs

**Comment by groovecoder** [comment]
We'll start with 100 tickets and open it up from there if/when we sell out.
