### ISSUE TITLE
Provide budget 

### ISSUE THREAD

**Issue by jdungan** [techlahoma/200ok#13]
@groovecoder to provide budget for breakfast, lunch and swag from last 200OK

**Comment by groovecoder** [comment]
From the expense report, the total was $5,743 (or $6,243 - see below). Detailed expense report is [online here](https://docs.google.com/spreadsheets/d/12Te-ZYDFit4GaKLtWzZjyuusqwQUQ6f76I4C2dpCfVU/edit#gid=0), but you'll need to request access.

* Speakers' Dinner @ Laffa: $515
* "After-party" drinks $443
  * Chimera: $393
  * Soundpony: $50
* (1) Speaker Travel: $857
* T-shirts: $1,055
* Tables/Chairs Rental: $900
* Snacks: $350
* Lunch: $1,262
* Flyloft Rental: $361

This was in the same expense report, but I'm checking with Scott to see if they were 200 OK items or something else.
* "TES Productions": $500

At 36°N we won't have a rental fee, and I assume 36°N will have all the tables & chairs we'll use.

So, a baseline budget may be $5,000.

**Comment by jwhitlock** [comment]
I think TES Productions was the crew videotaping the conference, but @sephillips should confirm.

**Comment by jsatt** [comment]
I thought @destos was the one videotaping.

**Comment by sephillips** [comment]
TES Productions rented us the screen and projector

From: Jeremy Satterfield
Reply-To: techlahoma/200ok
Date: Thursday, January 21, 2016 at 9:20 AM
To: techlahoma/200ok
Cc: Scott Phillips
Subject: Re: [200ok] Provide budget (#13)


I thought @destos<https://github.com/destos> was the one videotaping.

**Comment by groovecoder** [comment]
Since 36°N will provide the screen & projector, it sounds like $5k is the baseline to repeat like we did last time. (See https://github.com/techlahoma/200ok/issues/18 for recording video issue)
