### ISSUE TITLE
List of last 200 OK speakers

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#14]

**Comment by groovecoder** [comment]
* Lara Hogan, Etsy
* David Walsh, Mozilla
* Helen Hou-Sandi, 10up
* Jesse Cravens, Frog
* Michael Gorsuch, GitHub
* Local lightning talk speakers
  * TL Cox, CIO of Tulsa
  *

**Comment by groovecoder** [comment]
I could email these folks again and ask if they would want to speak again, and/or could refer us to a speaker they think would do well at 200 OK?

**Comment by jugisahunk** [comment]
Sounds good. I'll be working to get the cfp up again tomorrow.

**Comment by jugisahunk** [comment]
open cfp is up, but needs theming and some text configuration [here](http://192.241.179.236/)

**Comment by jugisahunk** [comment]
Started a list of potential speakers here:

[Potential Speakers](https://docs.google.com/document/d/1u2mFnerNWO6ZQ5_PW-syfnKrNVrzac_C0d5n11MK9O4/edit?usp=sharing)

**Comment by jugisahunk** [comment]
@amandaharlin and @the-simian are going to email last year's speakers advertising with new CFP for this year. Link to new task [here](https://github.com/techlahoma/200ok/issues/29).
