### ISSUE TITLE
Ask Amanda about getting Thunder Plains speaker list/email sent

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#15]

**Comment by groovecoder** [comment]
@amandaharlin when we stand up our own OpenCFP instance, can we get the ThunderPlains list loaded into it? Or should we just email your list and invite them to submit to 200 OK too?

**Comment by the-simian** [comment]
I'm thinking just email the list- We managed it with mail chimp, so its easy to compose and send there. We might also want to include lists from other campaigns, such as the techlahoma/javascript/etc lists.

We'll need to make sure you have access to that

**Comment by jugisahunk** [comment]
@amandaharlin would you like to take this task then? I'm working on getting the cfp marketing text edited to be more appropriate for 200OK.

**Comment by the-simian** [comment]
FYI @jugisahunk we're doing a long meeting this evening and friday looks busy also, so the soonest we can hit this will be probably the weekend
