### ISSUE TITLE
200 OK Tagline + description of what the event is

### ISSUE THREAD

**Issue by TatumCreative** [techlahoma/200ok#16]
Last tagline was:

> 200 OK connects South-by-Midwest web professionals with some of the best speakers in the country for a day of presentations about leading web technology topics.

Any ideas on a bigger description?

**Comment by groovecoder** [comment]
I like that tagline alright, though I've fallen out of love with the South-by-Midwest moniker. The View Source paragraph is good inspiration ...

>At View Source you’ll be inspired by what’s to come. Join us and learn to build a web that’s more powerful, accessible, and secure using modern techniques that work today and will thrive tomorrow. We learn best from each other, so View Source will provide plenty of time and space for interaction and conversation. In addition to awesome talks, there will be an ongoing hacking space, demos, and group discussions, as well as fun evening activities. Thanks to all of our speakers, sponsors, volunteers, staff and attendees for an awesome event!

So how about ...

200 OK connects you with fellow web professionals and some of the best speakers in the country for a day of presentations about leading web technology topics. In addition to great talks, there will be hacking space and areas for break-outs and group discussions. Watch this space for more details ...

?
