### ISSUE TITLE
Recording Video

### ISSUE THREAD

**Issue by the-simian** [techlahoma/200ok#18]
I'd like to help some with this, unless you have a good solution already in mind. I did a lot of research during the last ThunderPlains to try and keep the setup inexpensive, but still functional and high quality. We ended up using a nontraditional setup where we screen-grabbed the computer with [ninjas](http://www.atomos.com/ninja/), and recorded the speaker with a camera, also going to a ninja. Both ninjas recorded audio, so in post you could use the automatically-line-up-my-tracks feature that most editors have. In this case, Premiere Pro.

Usually, quality turned out pretty good, you can see it here if you haven't.

[![kyle video](http://img.youtube.com/vi/C_yj4k4QZVI/0.jpg)](https://www.youtube.com/watch?v=C_yj4k4QZVI)

If we get someone to do the editing for us that's cool, but if we need to do any I can provide all the premiere pro templates/ps templates and things being used.

Of course the gear we have currently is at our disposal, and if we need to rent more, or need access to folks willing to operate the cameras I can probably arrange that. What is necessary is contingent on the space's capabilities as well as how many tracks we have.

Whatever is decided I figured getting an issue going here is a good start.

When I am done editing all the TP videos (I honestly got a bit behind when Ada was born, but I'm moving full steam ahead now), I planned on writing a blog post explaining the setup, how it works, and how to make use of it in the video editor quickly. By that i mean, using the multicamera editing features most good editors have, so it doesn't take nearly as long.

Edit: I just remembered that another option, if someone is willing to attempt this, is we also have a licence to VMix, which offers live editing and streaming functionality. That was not a good option for us at the Cox Center, but in a more controlled setup, maybe it could be. The ninjas work great anywhere, and we are currently using them at usergroups.

**Comment by groovecoder** [comment]
Labeling this for the speakers team.

Last time @destos recorded and Scott helped him with the audio capture, IIRC.

**Comment by destos** [comment]
We were never able to use the footage because the audio recording ended up getting high spikes which made them unusable. The audio from the camera wasn't acceptable either due to being a consumer camcorder. We should attempt a more professional solution this time.

**Comment by jugisahunk** [comment]
I'm speaking with a guy who produced the sound capture for Greyscale

http://m.imdb.com/title/tt1321390/

It is a movie I was part of a few years back. His name is Mark Gullickson
and he's told me he would be interested in helping us up or game.

Are you all interested in bringing him into the conversation?

**Comment by the-simian** [comment]
I guess the most important question I have is: how many tracks are there?
the second one is : is there any live sound reinforcement already at the venu?

If there is one track, we already have access to gear necessary to do a good capture of both video and audio. This is assuming you consider the video I posted above to be adequate quality. You need 2 ninjas, a camera, a lapel and 2 drives, one drive for each ninja. (The ninjas help a lot even for the camera: This way you're not repeatedly swapping out sd cards and dumping, which is a huge waste of time in a live scenario). If there are more tracks, you'll need to replicate whatever setup in more rooms. We rented, but whatever works.

You'll also need a person to operate the camera that captures the actual speaker (not the slides). We had 2 volunteers and one paid individual to do this, because w had 3 tracks.

All you need or the speaker audio is an adequate lapel. I my opinion: A boom mic- scenario or other complex setup is expensive overkill, and requires more operators.  

That's live capture concerns. Editing and post are different concerns. And live sound/av reinforcement are separate concerns.

On editing: 
I'll be honest - editing takes a while. I've been trying to develop streamlined solutions to make this part of the process more accessible to usergroups. That's a conversation for another time, for now you'll want someone that either you pay or is willing to edit the conference. It sounds like @jugisahunk has some contacts that would be useful here. 

If ya'll decide to edit, its not impossible- just work. You can use any of my project files, etc.

On live sound reinforcement:
If this team is also responsible for live sound reinforcement, that could alter the nature of the setup. You could use the lapel, and rather than running it to the slides-capturing-ninja, run that to the mixer, and then aux send from the mixer to the ninja. You could probably just rent a couple powered speakers and go main out into those for output - something similar to the well known mackie SRM's or the QSC K series. A smaller venu could use like a fender passport.  Anything more is overkill, unless you're planning to have a band play or something like that.

**Comment by the-simian** [comment]
I'll tell you what - when I get a chance I'll draw a diagram and post it here, so there's not a lot of mental assembly required to track the setup. you're free to follow, or not follow it -but In my experience its the simplest, most inexpensive way to achieve a high quality recording. (HD,but not 4k,  in this case)

**Comment by groovecoder** [comment]
There's a video recorder here at 36°N who records all of the 1MC talks here. We'll ask him to do 200 OK talks too.

**Comment by groovecoder** [comment]
I have Rick Shadle lined up to record and live-stream for us. Meeting with him later today for final logistics.
