### ISSUE TITLE
(Re-) Start website

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#2]
I own the 200ok.us domain. @destos is leading the team to make the website. I can point the domain wherever we want.

**Comment by groovecoder** [comment]
@destos or @TatumCreative - to whom should I assign this? We'll want to put information about:

* Date & place
* CFP (when it's ready)
* Sponsorship Prospectus
* Eventbrite(?) RSVP button

up as soon as we can.

**Comment by the-simian** [comment]
FYI, we used hexo and pushed to gh pages for just about every ug site we have. All the themes and everything are sitting here in the techlahoma repos, and we put some basic tutorials on updating in the repos also. Basically using gh-pages is perfectly free, and keeps everything right here in one place, so I certainly like it.

Feel free to use any as a starting point. You can have a site up and running within an hour

**Comment by groovecoder** [comment]
I love GH Pages. You used it for ThunderPlains site too?

**Comment by the-simian** [comment]
@groovecoder yep -all of them!

**Comment by TatumCreative** [comment]
@the-simian I was thinking gh-pages + hexo is the route to go for sure. @destos when do we start and under what repo? I think it would be good to kickstart it with some base theme to get us going. It would also be nice to have a content doc to get us going. @chimchim237 what's the status on art assets? Are we using the same stuff from last time? It would be nice to have a mood-board or style tile and then marry that to a theme. At the very least we can get up a splash page with date.

**Comment by groovecoder** [comment]
Yeah, would be great to have a splash page up ASAP. I'll add a link to sponsorship prospectus when it's up. I suggest techlahoma/200ok.us as the repo.

**Comment by destos** [comment]
Doesn't look like I have permissions to create a repo. I think we should be able to get something up tonight with old logo as a splash page.

**Comment by the-simian** [comment]
let me fix that

**Comment by the-simian** [comment]
ok, @techlahoma/200ok I made a team but I haven't messed with owner privileges yet - but @groovecoder can already do that and also make repos too as of now

**Comment by the-simian** [comment]
@techlahoma/200-ok  I made one: https://github.com/techlahoma/200ok-site

**Comment by TatumCreative** [comment]
Great, if anyone has a copy of the logo somewhere I can throw together a splash page to get us going.

**Comment by rhoegg** [comment]
Would these work? https://github.com/techlahoma/techlahoma_assets

**Comment by TatumCreative** [comment]
I'm looking for the 200ok logo, although those probably will come in handy.

**Comment by destos** [comment]
Here's the old one for now.
![200ok](https://cloud.githubusercontent.com/assets/136456/12363288/99380a12-bb8d-11e5-9b7f-3e49b19b4c5f.png)

**Comment by TatumCreative** [comment]
No vector I'm assuming.

**Comment by TatumCreative** [comment]
http://techlahoma.github.io/200ok-site/

Splishy splashy page is started.

**Comment by groovecoder** [comment]
awesome! (also, is splishy splasy an Eddie Izzard reference?)

The most immediate things to add seem to be?

* Sponsors
  * Mozilla [Logo terms of use](https://www.mozilla.org/en-US/styleguide/identity/mozilla/branding/)
  * Sponsorship Prospectus - convert [wiki draft](https://github.com/techlahoma/200ok/wiki/Sponsorship-Prospectus-Draft) to a page or a pdf download?
  * Link for sponsors to send us sponsorship request (email organizers@200ok.us? file github issue?)
* RSVP link for attendees
  * Eventbrite?
* Link to OpenCFP for speakers

**Comment by groovecoder** [comment]
Updated DNS: http://200ok.us/

**Comment by TatumCreative** [comment]
Initial sponsors and [sponsorship prospectus](http://200ok.us/sponsorship-prospectus/) online now.

**Comment by groovecoder** [comment]
Awesome! So when do we close this issue and start making individual issues for changes? :smile:

**Comment by TatumCreative** [comment]
Sounds good!
