### ISSUE TITLE
Customize template text for 200OK specifically

### ISSUE THREAD

**Issue by jugisahunk** [techlahoma/200ok#21]
Much of the template text needs to customized as per 200ok policy. For example, the [speaker package](http://192.241.179.236/package) page may need changing based on how we intend to support our speakers.

Also, the [talk ideas](http://192.241.179.236/ideas) page needs some customizing.

**Comment by jugisahunk** [comment]
@groovecoder and I will connect tonight to work on copy changes.

**Comment by jugisahunk** [comment]
Current copy in Google doc for editing and comment [here](https://docs.google.com/document/d/1UTRanyPPv1yaAr6Mqe6W1SMWCAQEHlA2MyxwcDFARUc/edit?usp=sharing).

**Comment by groovecoder** [comment]
The doc is looking good to me.

**Comment by jugisahunk** [comment]
Got it.

*Jason Knight*

*Scrum Master*
*Vitals* | The Thompson Building 20 E. 5th St., Suite 430 Tulsa OK, 74103

W: 918.932.3850 | C: 918.606.4463

http://www.vitals.com
