### ISSUE TITLE
Fill in OK Coders workshop agenda

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#22]

**Comment by groovecoder** [comment]
@sergei-jobpact I can't remember if you sent me this, or if we need to add it here?

**Comment by sergei-jobpact** [comment]
@groovecoder: This is the rough agenda I have for the course, let me know if you need more details or a more engaging title:

Building an Asteroids game with HTML5 Canvas:
- HTML5 Canvas introduction
- Basic shapes and drawing
- Animation with Canvas
- Adding enemies and tracking states
- Collision detection
- Bringing the game to life

Depending on class size/speed, this may only take up the first 4 hours; if that's the case then we'll spend the second 2-hour block on things like sound and better graphics or possibly open Q/A.

**Comment by groovecoder** [comment]
@sergei-jobpact - I updated the OK Coders workshop details on the site with these details.

https://github.com/techlahoma/200ok-site/pull/29

It's live on http://200ok.us/#schedule ... Re-open here or submit a PR if you want to change or update it.
