### ISSUE TITLE
Reach out to Dallas Crowd for Speakers

### ISSUE THREAD

**Issue by jugisahunk** [techlahoma/200ok#24]

**Comment by groovecoder** [comment]
@jugisahunk - were you able to reach Dallas crowd with a link to CFP?

**Comment by jugisahunk** [comment]
I did a few weeks back, but haven't heard back. I just posted in a big meetup group with over a thousand members. We'll see if that request get's any traction.

[http://www.meetup.com/DFWScrum/messages/boards/thread/49726359](http://www.meetup.com/DFWScrum/messages/boards/thread/49726359)

**Comment by groovecoder** [comment]
Cool, I think we can close this now.

**Comment by groovecoder** [comment]
Thanks!
