### ISSUE TITLE
Final design for t-shirt

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#28]

**Comment by jsatt** [comment]
for the prints they need:
"300 dpi at whatever size you want printed as a .psd, jpeg or tiff. That or an illustrator file assuming it's made in vector."

**Comment by groovecoder** [comment]
ping @chimchim237 - any time on this yet? We've got all of March to do it; just curious while we're here at hack night ...

**Comment by groovecoder** [comment]
ping @chimchim237 - any chance to hit this yet?

**Comment by groovecoder** [comment]
@chimchim237 any time to get this design done?

**Comment by jsatt** [comment]
@groovecoder, @chimchim237. Any update on this? We're coming into the home-stretch and need to get the order over to Flash Flood.

**Comment by chimchim237** [comment]
[200OK shirt design (2016).pdf](https://github.com/techlahoma/200ok/files/249086/200OK.shirt.design.2016.pdf)
![200ok shirt concept](https://cloud.githubusercontent.com/assets/8526129/15019728/c89bd1dc-11e4-11e6-9271-73edf5122cac.png)

**Comment by chimchim237** [comment]
[https://www.dropbox.com/sh/u7rcgsdbl52qtd5/AACFJ2cAyvvziPLRQaMXPLfIa?dl=0](url)

**Comment by chimchim237** [comment]
@groovecoder @jsatt lemme know if you think we need to run the back of the shirt by the sponsors for approval.

**Comment by groovecoder** [comment]
Maybe, but I'm sure it will be easy. Only GKFF, 36°N, and Techlahoma will be on the shirt ...

**Comment by groovecoder** [comment]
We got the shirt design file to Flash Flood today.

Sheet with final shirt quote: https://docs.google.com/spreadsheets/d/162ZeMHMtL3FBv0lD3cl4cdPGkogwIqsct--pnWCIuDM/edit#gid=0 i.e. - It will be ~$1,250 for 120 shirts of 50/50 cotton/poly.

We confirmed with Flash Flood, so I think we're good here, right? We can close this?

**Comment by chimchim237** [comment]
I'm good with closing this; yes.
