### ISSUE TITLE
List previous 200 OK sponsors and request follow-up sponsorships

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#3]
* [x] Mozilla
  * event sponsorship request bug filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1238270
* [x] ~~i2E~~
  * budget cuts; asking to connect us to their network of start-ups and/or angel investors who may want to sponsor
* [x] WordPress
  * emailed Rebecca Collins (our contact last year)
* [x] GitHub
  * emailed Elizabeth Naramore (our contact last year)
    * https://community.github.com/ (needs website url working)
* [x] Isocentric Networks
  * emailed that one guy
* [x] Anspire
  * emailed Doug Morrison

**Comment by groovecoder** [comment]
Note @TatumCreative @destos: the form for GitHub sponsorship needs the website url to be up and working

**Comment by jugisahunk** [comment]
My boss, Nathan Phelps may be interested in sponsoring on behalf of Vitals.com. Shall I reach out to him?

**Comment by groovecoder** [comment]
@jugisahunk that would be great, thanks!

**Comment by groovecoder** [comment]
From GitHub:
>Thanks for your sponsorship request!
>The Community team is currently looking over the details of your request. If your event is a good fit for us and we have the bandwidth to support it, one of the team will be in touch soon to follow up and get the ball rolling.
>Sincerely,
>The GitHub Community Team

**Comment by groovecoder** [comment]
I've now opened follow-up sponsorship requests with all our previous sponsors. So I'm going to close this issue and keep https://github.com/techlahoma/200ok/issues/7 open for new sponsors. (Including Vitals.com)
