### ISSUE TITLE
Add a big "Submit a talk" button to the home page

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#31]
Both the "Register Now" and "View Submissions" buttons on the home page go to the dashboard/profile page.

So, we should add a big button "Submit a talk" button that goes straight to http://speakers.200ok.us/talk/create

**Comment by jugisahunk** [comment]
Dang, just sawy htat @TatumCreative took this. I've added one, but it looks a bit like a 3rd grader designed my layout :)

http://speakers.200ok.us/

@TatumCreative, you can submit a pull request here to work on it if you'd like to help me improve the layout:

[https://github.com/jugisahunk/200OK_CFP.git](https://github.com/jugisahunk/200OK_CFP.git)
