### ISSUE TITLE
Pick a ticket price

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#33]
We've proposed $75 as the ticket price. Does that sound good?

**Comment by groovecoder** [comment]
https://docs.google.com/spreadsheets/d/19YVjacHwzyM8YEGaH8KF4Ci_C0GiC5HJ_jI9g_vxF9U/edit#gid=0

**Comment by groovecoder** [comment]
And $30 for OK Coders workshop price.

**Comment by groovecoder** [comment]
$75 early-bird; $100 regular.

**Comment by seven1m** [comment]
Tickets are created in ti.to :+1:

**Comment by rhoegg** [comment]
We like to offer some student scholarships, are we counting those as the
OKCoders on the spreadsheet? Or should we budget for a few "normal"
students to draw from colleges and even high school?

**Comment by groovecoder** [comment]
Hmm ... yeah we should count them as early-bird ticket sales I think. So we can give them 50-100% off and recruit them during the early bird sale period. Then we'll sell the rest of the regular tickets at full price.
