### ISSUE TITLE
Propose and fill in agenda

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#34]
Fill in day timeline of talks & times

**Comment by jsatt** [comment]
@groovecoder do we still have the agenda from last time?

**Comment by jsatt** [comment]
Here's the initial thoughts, we can work from here. This assumes 5 Speakers + 1 lightning talk session, w/ Q&A and transition time, and 2 hour lunch.

https://docs.google.com/spreadsheets/d/1pJwVJyHdUSLQwE4QEsXeKUWRcyC7kV3y68gEz0R3UO8/edit?usp=sharing

**Comment by groovecoder** [comment]
Made a couple comments (asking Scott if he has bandwidth for CIO breakfast,
and suggesting 1h 20m for on-site catered lunch) but this looks really good
to me. Thanks Jeremy!

**Comment by jsatt** [comment]
I added a couple of new proposals based on your suggestions.

**Comment by groovecoder** [comment]
I like:
  * 40-minute talks
  * 20-minute buffers
  * 1h 20m lunch
  * No lunch speaker
  * Closing remarks before 5pm
  * Leave a 20-30m "networking" buffer time before 5pm so people can still connect with each other, but don't feel like they have to stay past 5pm to do so

**Comment by groovecoder** [comment]
Final agenda is in the doc!!

https://docs.google.com/spreadsheets/d/1pJwVJyHdUSLQwE4QEsXeKUWRcyC7kV3y68gEz0R3UO8/edit#gid=0

**Comment by seven1m** [comment]
| Start Time    | Description            | 
|--------------|-----------------------| 
| 7:00:00 AM   | CIO Breakfast         | 
| 8:00:00 AM   | Registration Open     | 
| 8:50:00 AM   | Opening Remarks       | 
| 9:00:00 AM   | Speaker 1             | 
| 9:40:00 AM   | Q&A/Transition        |
| 10:00:00 AM  | Speaker 2             | 
| 10:40:00 AM  | Q&A/Transition        | 
| 11:00:00 AM  | Speaker 3             | 
| 11:40:00 AM  | Q&A/Transition        | 
| 12:00:00 PM  | Lunch                 | 
| 1:20:00 PM   | Lightning talks       | 
| 2:20:00 PM   | Speaker 4             | 
| 3:00:00 PM   | Q&A/Transition        | 
| 3:20:00 PM   | Speaker 5             | 
| 4:00:00 PM   | Q&A/Transition        | 
| 4:20:00 PM   | Closing Remarks       | 
| 4:30:00 PM   | Socialzing/Networking |  
| 5:00:00 PM   | After Party           |
