### ISSUE TITLE
Talk to Prairie Brewpub about drink tickets for after-party

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#39]

**Comment by groovecoder** [comment]
I talked to Ryan @ Prairie. He's concerned about the potential max # of people we would send over - i.e., 70-100. Adding that to a First Friday Art Crawl day would be pretty rough on them - they're still not quite into a routine yet. I told him we're more likely to see ~30 people go over - not the full 70-100.

He's going to meet with the other owners & managers and see what they think.

@jsatt - did we already ask Chimera too?

**Comment by jsatt** [comment]
I mentioned it to Jack (one of the owners) and he said he was fine with it based on how well it went last time, but we should still check in to give them a heads up. Maybe make sure whoever the manager on shift that night is aware.

**Comment by groovecoder** [comment]
I confirmed with Prairie today.

**Comment by groovecoder** [comment]
We should confirm with Prairie and Chimera staff on Thursday/Friday so they know what to expect and look for. Maybe at lunch on those days?
