### ISSUE TITLE
Stand up CFP

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#4]
Assigning this to Amanda for now, but I think Brian or Jason should take it over. Also needs link from website.

**Comment by the-simian** [comment]
we used open CFP last year, and it was really nice. [https://github.com/opencfp/opencfp ](https://github.com/opencfp/opencfp)

**Comment by jugisahunk** [comment]
I'd like to help with this one, but I need some direction on how opencfp was set up last year e.g. hosting choice. Ideally, I could pair with @amandaharlin or @the-simian to learn it while doing. Would either of you be available to help me learn this stuff?

**Comment by vlucas** [comment]
I setup OpenCFP on my own server last year, and pointed a subdomain to it with an A record ( the site was http://cfp.thunderplainsconf.com ). I can do the same this year too, or we can setup a $5 DigitalOcean VPS for it, etc.

**Comment by jugisahunk** [comment]
Got it. I was looking into using Heroku hosting, but I'm more familiar with DigitalOcean anyway. The $5 vps sounds like the way to go, so you don't get roped into too much work ;).

**Comment by groovecoder** [comment]
@jugisahunk - does this mean you'll make the server and deploy OpenCFP there? Or are you looking to assign that to someone else?

**Comment by jugisahunk** [comment]
I was going to just make it happen. I may need to get some help if I run into issues, since I'ver never messed with openCFP before.

I've assigned this task to myself.

**Comment by groovecoder** [comment]
Thanks @jugisahunk. Let us know if you need any help. I'm sure we have folks who can help you if you get stuck.

**Comment by groovecoder** [comment]
Any more luck on this? I'd like to start asking for more sponsors, but I'd also like to have our speakers link up so the sponsors can see we're in the process of getting speakers. :)

**Comment by jugisahunk** [comment]
I got sidetracked with work stuff last week. My bus is leaving our company
and the transform has taken a lot of my attention.

I'll start back on the cfp tomorrow. I've got the vsp and post of initial
setup done.

**Comment by jugisahunk** [comment]
Ok, I'm trying to get Apache configured properly: http://192.241.179.236/

I've got a speakers.200OK.us.conf file setup in sites-available. Here are the directives:

ServerAdmin webmaster@localhost
DocumentRoot /var/www/speakers.200ok.us/public_html
ServerName 192.241.179.236
ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

When I hit the url, I only see the file directory and accessing the /web directory gives me a 500 error. I'm not an apache or a php guy, so a little help would be nice :smile:

**Comment by jugisahunk** [comment]
Progress made; the site is up. Needs further config, but it's not erroring out any more:

[http://192.241.179.236/](http://192.241.179.236/)

**Comment by jugisahunk** [comment]
It's good to go for now, but needs template tweaks. We'll want to examine working here and there and match the 200ok.us theme.

I'll close this out and make a couple more tasks for those actions.

**Comment by groovecoder** [comment]
Added CNAME for http://speakers.200ok.us/

**Comment by jsatt** [comment]
That doesn't seem to have worked. It's accessible from via the IP, not the DNS. I'm pretty sure that should be an A record, not a CNAME

**Comment by jsatt** [comment]
Also if the line `ServerName 192.241.179.236` is still in the config, that's going to be a problem as well.

**Comment by jugisahunk** [comment]
yes, it is. I'll change it to http://speakers.200ok.us

**Comment by jugisahunk** [comment]
Done:

```
ServerAdmin webmaster@localhost
DocumentRoot /var/www/html/web
#ServerName 192.241.179.236
ServerName speakers.200ok.us
```

**Comment by jsatt** [comment]
Do you restart Apache?

**Comment by jugisahunk** [comment]
yessir :smile:

**Comment by jugisahunk** [comment]
I am getting this message after restarting apache though:

`AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message`

Would that affect anything?

**Comment by jugisahunk** [comment]
Seeing this article on the warning message:

[http://askubuntu.com/questions/329323/problem-with-restarting-apache2](http://askubuntu.com/questions/329323/problem-with-restarting-apache2)

Should I update the httpd.conf file to "speakers.200ok.us"?

**Comment by groovecoder** [comment]
I changed the `CNAME` to an `A` record.

**Comment by jsatt** [comment]
domain is working for me, looks like the copy still needs tweaking, but otherwise LGTM.
