### ISSUE TITLE
First Contact with new sponsors

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#7]
## General
* [x] Mozilla
  * [ ] Thank-you posts
* [x] Google
* [x] Microsoft
* [x] Apple
* [x] New Relic
* [x] Heroku
* [x] Cloud Foundry
* [x] TYPros / Tulsa Chamber
* [x] gitwit
   * [ ] Thank-you post

## Local/Oklahoma
* [x] GKFF
  * [ ] Thank-you posts
* [x] Tulsa Chamber
* [x] Vitals.com
* [x] TierPoint
* [x] codesy
  * [ ] Thank-you posts
* [x] interworks
* [x] tailwind
* [x] iThemes
  * [ ] Thank-you posts

## Civic
* [ ] Accela
* [ ] Socrata
* [ ] Esri
* [ ] OpenDataSoft

**Comment by groovecoder** [comment]
@TatumCreative we need to tweet Thank-You to iThemes - they just agreed to sponsor. Should we just tweet it, or set it up in a buffer queue?

**Comment by DevinClark** [comment]
If you queue through buffer, you get pretty good analytics.

**Comment by TatumCreative** [comment]
Personally, I'm not too concerned with analytics so I'd say just tweet it. Otherwise I can put it into the buffer.
