### ISSUE TITLE
Social Media

### ISSUE THREAD

**Issue by gregtatum** [techlahoma/200ok#8]
Are we just doing twitter for this one? It'd be nice if @destos and I could get access to it. Not sure when we want to start actively promoting the event.

**Comment by groovecoder** [comment]
I've forgotten the password, so let me mess around with it a bit to get access back to it and I'll share the creds with promo team.

**Comment by groovecoder** [comment]
Couldn't guess the password, I've lost access to the email address, so I emailed Twitter support. :neutral_face:

**Comment by groovecoder** [comment]
Wow, Twitter account recovery is tough. They won't let me back into the account unless I have the old email inbox (I don't), or guess the password (I can't).

How do we feel about making a new twitter account? @200okus ?

**Comment by TatumCreative** [comment]
Woops! I guess that will have to do.

**Comment by jdungan** [comment]
okus? Looks weird

**Comment by groovecoder** [comment]
@200okevent? Since we hope to be more than a conference right?

**Comment by the-simian** [comment]
hey, I wante to add that using buffer for the conference account was invaluable to us. At one point I did a drip campaign with over 100 tweets. I also tried to align tweets  with times that were highest in traffic
![tweetin](https://cloud.githubusercontent.com/assets/954596/12462463/0d23ccf0-bf84-11e5-938d-85c3eeccacac.png)

Also included some middle-of-the-night ones. Every speaker would be represented in the morning, noon, evening at some point.

This was also a good tool to fulfill sponsor obligations to tweet, in a measurable strategic way.

You can also attach other social media items to buffer  like facebook, g+ , etc. This is with the buffer-awesome plan. Its 102$ a year. You can do 10 for free, but when the vent draws near, you'll probably want the extra ones. It helped a lot, I recommend using it for 200ok also.

**Comment by TatumCreative** [comment]
Awesome, thanks @the-simian, I was thinking of using Buffer, great to hear that it worked out well. @groovecoder what do you think about getting a paid account?

**Comment by the-simian** [comment]
I don't know if this is useful, but I wanted to share that for twitter, we found the ideal image size to be 1024 x 512. Its big enough to touch the sizes, but no truncation.
![d8c9b074b6a85b3a1b121744df54b461 dcf9b97478b93871fb31fb52fcd80138](https://cloud.githubusercontent.com/assets/954596/12463037/12215738-bf87-11e5-8240-f2cedf101988.jpg)

We made 'twitter cards' like that for each speaker and used them in the campaign. Ended up keeping them [with all the speaker assets in the website](https://github.com/techlahoma/thunderplains-2015/tree/master/source/speakers) alongside the headshots and stuff.

**Comment by groovecoder** [comment]
Do we still have a Techlahoma buffer account?

If we're good with @200okevent I'll sign us up for that now.

**Comment by TatumCreative** [comment]
Works for me.

**Comment by groovecoder** [comment]
https://twitter.com/200okevent lives. I'll send the pw out of band

**Comment by amandaharlin** [comment]
I'll send over the pw manager link for twitter and buffer! :-)

**Comment by groovecoder** [comment]
@amandaharlin did you send that to @TatumCreative too?

**Comment by groovecoder** [comment]
We recovered https://twitter.com/200okconf thanks to @seven1m. @amandaharlin - were you able to send the the twitter/buffer access to @TatumCreative ?

**Comment by groovecoder** [comment]
@amandaharlin: ping again - do we have the twitter/buffer access for @TatumCreative to manage the 200okconf handle?

**Comment by groovecoder** [comment]
@amandaharlin @TatumCreative - did we get the twitter pw and buffer account squared away here? do you have what you need to buffer some tweets for 200okconf?

**Comment by carlosangon** [comment]
![200ok-01](https://cloud.githubusercontent.com/assets/2627624/14924555/cf515838-0e08-11e6-9caa-82a98493329a.png)

@groovecoder and @TatumCreative 

There you guys go, let me know if you need me to create anything else.

- C

**Comment by groovecoder** [comment]
Thanks @carlosangon.

@TatumCreative - can you queue this up in the buffer?

**Comment by carlosangon** [comment]
@TatumCreative Let me know if you need me to resize the graphic to any specific dimensions.

- C

**Comment by carlosangon** [comment]
Ok @groovecoder and @group 

I'm about to be putting together the tweet cards for the speakers and sponsors and I'd just like some feedback on which orientation I should proceed with.

Thanks

- C

Portrait or Landscape.
![200ok-04](https://cloud.githubusercontent.com/assets/2627624/14939043/3ab1a066-0efd-11e6-843b-b9b4ea0f2b1e.png)
or
![200ok-05](https://cloud.githubusercontent.com/assets/2627624/14939046/44e2b78c-0efd-11e6-8145-6060a055c3ca.png)

**Comment by TatumCreative** [comment]
I'd go for the landscape so things don't get cut off, thanks for doing this!

**Comment by groovecoder** [comment]
:+1: landscape. looks great!

**Comment by carlosangon** [comment]
Let me know what you think of these. I'm still working on the sponsors cards. I had to come out with a creative solution to work around the inconsistent quality of the speakers images.

- C

Please review and provide feedback.


![200ok-05](https://cloud.githubusercontent.com/assets/2627624/14973297/ab1dbb64-10ab-11e6-8686-d80ec4ca4196.png)
![200ok-06](https://cloud.githubusercontent.com/assets/2627624/14973301/ab1fa1b8-10ab-11e6-9b3e-23de09dd3d4b.png)
![200ok-07](https://cloud.githubusercontent.com/assets/2627624/14973298/ab1ee304-10ab-11e6-9c9a-5c9903833588.png)
![200ok-08](https://cloud.githubusercontent.com/assets/2627624/14973302/ab2241e8-10ab-11e6-8228-8116f5db47f5.png)
![200ok-09](https://cloud.githubusercontent.com/assets/2627624/14973300/ab1f4dc6-10ab-11e6-96a0-39c0d4c7ec14.png)
![200ok-10](https://cloud.githubusercontent.com/assets/2627624/14973299/ab1efac4-10ab-11e6-944e-8ab66240b13c.png)
![200ok-11](https://cloud.githubusercontent.com/assets/2627624/14973303/ab2b2a74-10ab-11e6-9d73-34885815647b.png)
![200ok-12](https://cloud.githubusercontent.com/assets/2627624/14973305/ab2d4520-10ab-11e6-940b-7b947d6f9aa0.png)
![200ok-13](https://cloud.githubusercontent.com/assets/2627624/14973306/ab2de0a2-10ab-11e6-929b-8665b187561b.png)
![200ok-14](https://cloud.githubusercontent.com/assets/2627624/14973307/ab2e2580-10ab-11e6-86e9-3b78c3298c29.png)
![200ok-15](https://cloud.githubusercontent.com/assets/2627624/14973304/ab2d0d62-10ab-11e6-8cc3-d58430e856e3.png)
![200ok-16](https://cloud.githubusercontent.com/assets/2627624/14973308/ab329a5c-10ab-11e6-9229-c5ca69c7e8dc.png)

**Comment by groovecoder** [comment]
These look great!

**Comment by groovecoder** [comment]
I'm going to close https://github.com/techlahoma/200ok/issues/7 but it has the list of sponsors we should thank via social media posts.

**Comment by carlosangon** [comment]
I just finished up the Sponsors graphics. Sorry it took so long guys. 🤘

Again, feedback, comments, or any edits are welcome. I hope I didnt forget anynone.
If I did, please let me know. 

![200ok-17](https://cloud.githubusercontent.com/assets/2627624/15092332/382a0ed0-142c-11e6-96d4-30a732d33858.png)
![200ok-18](https://cloud.githubusercontent.com/assets/2627624/15092327/38274312-142c-11e6-95bb-e5a400a645d6.png)
![200ok-19](https://cloud.githubusercontent.com/assets/2627624/15092331/38283178-142c-11e6-9f15-193205e0cc72.png)
![200ok-20](https://cloud.githubusercontent.com/assets/2627624/15092328/38274cae-142c-11e6-8b28-d52219c4cef0.png)
![200ok-21](https://cloud.githubusercontent.com/assets/2627624/15092330/3827d980-142c-11e6-9200-59fca7961a95.png)
![200ok-22](https://cloud.githubusercontent.com/assets/2627624/15092329/382774fe-142c-11e6-9f9d-273b96d886fc.png)
![200ok-23](https://cloud.githubusercontent.com/assets/2627624/15092334/3835691a-142c-11e6-8dba-42bfcc802fdb.png)
![200ok-24](https://cloud.githubusercontent.com/assets/2627624/15092333/3834a8ea-142c-11e6-847a-ab84eefb17e8.png)







.

**Comment by groovecoder** [comment]
These also look great. Thanks again!

**Comment by carlosangon** [comment]
@groovecoder Np, let me know if you need anything else.

- C

**Comment by groovecoder** [comment]
@carlosangon - can you make another sponsor thank-you tweet for Robert Half, using the same logo that's on the site? http://200ok.us/#sponsors

**Comment by carlosangon** [comment]
There you go.

- C

@groovecoder 


![200ok-25](https://cloud.githubusercontent.com/assets/2627624/15407732/110a4856-1dd2-11e6-8210-88b455c6cefc.png)

**Comment by groovecoder** [comment]
@carlosangon - can we get 1 last speaker card made? One for me:

http://200ok.us/speakers/luke-crouch.html

**Comment by the-simian** [comment]
I just wanted to say these all look really nice!

**Comment by carlosangon** [comment]
Thanks @the-simian !! 👍

**Comment by carlosangon** [comment]
@groovecoder There you go! 

- C

![200ok-27](https://cloud.githubusercontent.com/assets/2627624/15723967/868d05ea-280a-11e6-923f-433f6be1ca6e.png)
