### ISSUE TITLE
Start ti.to event

### ISSUE THREAD

**Issue by groovecoder** [techlahoma/200ok#9]
Let's not publish it openly yet, so we can get some promotion channels going for TU, OKC, etc.

**Comment by amandaharlin** [comment]
@groovecoder i created a private ti.to event. you should have an admin email invite in your inbox. you can manage teams in tito too. so add moderators and users to the 200ok team as you need,

**Comment by amandaharlin** [comment]
also the private event is current under this url: https://ti.to/techlahoma/200-ok didn't know if you wanted the dash removed. it's something we can change at any time.

**Comment by groovecoder** [comment]
Thanks. I added @jdungan @TatumCreative and @seven1m to the 200 OK team.

**Comment by jdungan** [comment]
Add Tim Morgan too. Pls.

**Comment by groovecoder** [comment]
I did. He's @seven1m. (71m)

**Comment by seven1m** [comment]
:+1: thanks

**Comment by amandaharlin** [comment]
awesome 😊
